name: Build and Publish Docker Images

permissions:
  packages: write

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      # Prevent a failure in one image from stopping the other builds
      fail-fast: false

      matrix:
        include:
          - image: Omost
            context: .
            file: Dockerfile
            platforms: linux/amd64,linux/arm64
            device: cpu

          - image: Omost
            context: .
            file: Dockerfile
            platforms: linux/amd64
            device: cuda
            suffix: -cuda

          - image: Omost
            context: .
            file: Dockerfile
            platforms: linux/amd64
            device: rocm
            suffix: -rocm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        # Skip when PR from a fork
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from the tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          # Skip pushing when PR from a fork
          push: ${{ !github.event.pull_request.head.repo.fork }}
          build-args: |
            TARGET=${{ matrix.device }}
          tags: |
            ghcr.io/${{ github.repository }}-${{ matrix.device }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}-${{ matrix.device }}:latest
            ghcr.io/${{ github.repository }}-${{ matrix.device }}${{ matrix.suffix }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}-${{ matrix.device }}${{ matrix.suffix }}:latest
          labels: |
            org.opencontainers.image.title=Omost
            org.opencontainers.image.description=Omost
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.url=
